name: what_to_click
description: What-to-click.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  auto_route: ^7.8.4
  click_tracker:
    path: ../click_tracker
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_webrtc: ^0.9.47
  image: ^4.1.3
  path_provider: ^2.1.1
  screen_capturer: ^0.1.7
  uni_links: ^0.5.1
  uni_links_desktop: ^0.1.7
  url_launcher: ^6.2.2

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  lint: ^2.3.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
